@baseurl=http://localhost:8080

### Create Account 
POST {{baseurl}}/api/account HTTP/1.1
Content-Type: application/json

{
    "accountHolderName": "Kajal Talele",
    "balance": 30000.00
}

### Get Account By Id
GET {{baseurl}}/api/account/getAccountById/2 HTTP/1.1
Content-Type: application/json

### Get All Accounts
GET {{baseurl}}/api/account/getAllAccounts HTTP/1.1
Content-Type: application/json


### Deposit Amount
GET  {{baseurl}}/api/account/deposit/1/2000 HTTP/1.1
Content-Type: application/json

###Withdraw Amount 
GET  {{baseurl}}/api/account/withdraw/1/5000 HTTP/1.1
Content-Type: application/json

###delete Account 
DELETE  {{baseurl}}/api/account/delete/5  HTTP/1.1
Content-Type:  application/json 